CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE CART (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SESSION_ID CHAR(36) DEFAULT NULL,
    CONSTRAINT CART_PK PRIMARY KEY (SESSION_PRIMARY_ID, NAME),
    CONSTRAINT SPRING_SESSION_CART_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);


CREATE TABLE CART_ITEM (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) DEFAULT NULL,
    CART_ID CHAR(36) DEFAULT NULL,
    QUANTITY INT DEFAULT NULL,
    SUBTOTAL DECIMAL(19,2) DEFAULT NULL,
    PRODUCT_ID BIGINT DEFAULT NULL,
    CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID),
    CONSTRAINT CART_ITEM_FK FOREIGN KEY (CART_ID) REFERENCES CART (SESSION_PRIMARY_ID) ON DELETE CASCADE
)


